// build.ts — produces a standalone lvthn-chacha binary.

import { statSync } from 'node:fs';

process.stdout.write('Bundling worker...\n');

const workerBuild = await Bun.build({
	entrypoints: ['src/worker.ts'],
	target:      'browser',
	format:      'esm',
	minify:      true,
});

if (!workerBuild.success) {
	process.stderr.write('Worker build failed:\n');
	for (const msg of workerBuild.logs) process.stderr.write(`  ${msg.message}\n`);
	process.exit(1);
}

await Bun.write(
	'src/worker-bundle.ts',
	`// AUTO-GENERATED by build.ts — do not edit\nexport const WORKER_BUNDLE = ${JSON.stringify(await workerBuild.outputs[0].text())};\n`,
);

process.stdout.write('Building binary...\n');

const result = await Bun.build({
	entrypoints: ['src/main.ts'],
	compile: {
		outfile: './dist/lvthncli-chacha',
	},
});

if (!result.success) {
	process.stderr.write('Build failed:\n');
	for (const msg of result.logs) process.stderr.write(`  ${msg.message}\n`);
	process.exit(1);
}

const size = statSync('./dist/lvthncli-chacha').size;
process.stdout.write(`Built: ./dist/lvthncli-chacha  (${(size / 1024).toFixed(1)} KB)\n`);
