// build.ts — produces a standalone lvthn binary.
// Step 1: bundle Serpent worker
// Step 2: bundle ChaCha worker
// Step 3: compile binary

import { statSync } from 'node:fs';

async function bundleWorker(entry: string, out: string, label: string): Promise<void> {
	process.stdout.write(`Bundling ${label} worker...\n`);
	const build = await Bun.build({
		entrypoints: [entry],
		target:      'browser',
		format:      'esm',
		minify:      true,
	});
	if (!build.success) {
		process.stderr.write(`${label} worker build failed:\n`);
		for (const msg of build.logs) process.stderr.write(`  ${msg.message}\n`);
		process.exit(1);
	}
	const js = await build.outputs[0].text();
	await Bun.write(out,
		`// AUTO-GENERATED by build.ts — do not edit\nexport const WORKER_BUNDLE = ${JSON.stringify(js)};\n`,
	);
}

await bundleWorker('src/serpent/worker.ts', 'src/serpent/worker-bundle.ts', 'Serpent');
await bundleWorker('src/chacha/worker.ts',  'src/chacha/worker-bundle.ts',  'ChaCha');

process.stdout.write('Building binary...\n');
const result = await Bun.build({
	entrypoints: ['src/main.ts'],
	compile: { outfile: './dist/lvthn' },
});
if (!result.success) {
	process.stderr.write('Build failed:\n');
	for (const msg of result.logs) process.stderr.write(`  ${msg.message}\n`);
	process.exit(1);
}

const size = statSync('./dist/lvthn').size;
process.stdout.write(`Built: ./dist/lvthn  (${(size / 1024).toFixed(1)} KB)\n`);
