// build.ts — produces a standalone lvthn binary using Bun's compiler.

import { statSync } from 'node:fs';

// ── Step 1: Bundle worker.ts to a self-contained JS string ───────────────────
// Compiled Bun binaries cannot resolve Worker modules from the VFS at runtime.
// Bundling the worker to a string and spawning via Blob URL is the reliable fix.

process.stdout.write('Bundling worker...\n');

const workerBuild = await Bun.build({
	entrypoints: ['src/worker.ts'],
	target:      'browser',
	format:      'esm',
	minify:      true,
});

if (!workerBuild.success) {
	process.stderr.write('Worker build failed:\n');
	for (const msg of workerBuild.logs) process.stderr.write(`  ${msg.message}\n`);
	process.exit(1);
}

const workerJs = await workerBuild.outputs[0].text();

// Write as a TS module exporting the bundled string.
// Imported by pool.ts — embedded into the final binary as a string literal.
await Bun.write(
	'src/worker-bundle.ts',
	`// AUTO-GENERATED by build.ts — do not edit\nexport const WORKER_BUNDLE = ${JSON.stringify(workerJs)};\n`,
);

// ── Step 2: Compile the main binary ──────────────────────────────────────────

process.stdout.write('Building binary...\n');

const result = await Bun.build({
	entrypoints: ['src/main.ts'],
	compile: {
		outfile: './dist/lvthncli-serpent',
	},
});

if (!result.success) {
	process.stderr.write('Build failed:\n');
	for (const msg of result.logs) process.stderr.write(`  ${msg.message}\n`);
	process.exit(1);
}

const size = statSync('./dist/lvthncli-serpent').size;
process.stdout.write(`Built: ./dist/lvthncli-serpent  (${(size / 1024).toFixed(1)} KB)\n`);
