/**
 * build.ts: Bundle leviathan-crypto and assemble dist/index.html.
 *
 * Usage: bun run build.ts
 *
 * 1. Pre-bundles three pool workers (serpent, chacha20, aes) as IIFE strings
 *    so cipher-suites.js can spawn them via Blob URL (single-file HTML target,
 *    same trick lvthn CLI uses for Bun compile).
 * 2. Bundles leviathan.web-entry.ts -> leviathan.bundle.js
 * 3. Reads src/template.html, src/style.css, src/app.js
 * 4. Replaces placeholders and writes dist/index.html
 */

import { mkdirSync, statSync } from 'node:fs';

const entryPath    = './leviathan.web-entry.ts';
const bundlePath   = './leviathan.bundle.js';
const templatePath = './src/template.html';
const stylePath    = './src/style.css';
const scriptPath   = './src/app.js';
const outputDir    = './dist';
const outputPath   = './dist/index.html';

async function bundleWorker(entry: string, out: string, label: string): Promise<void> {
	process.stdout.write(`Bundling ${label} worker...\n`);
	const build = await Bun.build({
		entrypoints: [entry],
		target: 'browser',
		format: 'iife',
		minify: true,
	});
	if (!build.success) {
		process.stderr.write(`${label} worker build failed:\n`);
		for (const msg of build.logs) process.stderr.write(`  ${msg.message}\n`);
		process.exit(1);
	}
	const js = await build.outputs[0].text();
	await Bun.write(out,
		`// AUTO-GENERATED by build.ts, do not edit\nexport const WORKER_BUNDLE = ${JSON.stringify(js)};\n`,
	);
}

await bundleWorker(
	'node_modules/leviathan-crypto/dist/serpent/pool-worker.js',
	'src/workers/serpent-worker.js',
	'Serpent',
);
await bundleWorker(
	'node_modules/leviathan-crypto/dist/chacha20/pool-worker.js',
	'src/workers/chacha-worker.js',
	'ChaCha',
);
await bundleWorker(
	'node_modules/leviathan-crypto/dist/aes/pool-worker.js',
	'src/workers/aes-worker.js',
	'AES',
);

process.stdout.write('Bundling leviathan-crypto...\n');
const result = await Bun.build({
	entrypoints: [entryPath],
	outdir: '.',
	naming: 'leviathan.bundle.js',
	target: 'browser',
	format: 'esm',
});
if (!result.success) {
	for (const log of result.logs) process.stderr.write(log.message + '\n');
	process.exit(1);
}

const bundle   = await Bun.file(bundlePath).text();
const template = await Bun.file(templatePath).text();
const style    = await Bun.file(stylePath).text();

// app.js shares module scope with the inlined leviathan bundle. The three
// helper files (format/crypto/cipher-suites) reference exports from the
// bundle as ambient identifiers, so they are concatenated into a single
// {{APP_SCRIPT}} payload rather than imported.
const formatJs       = await Bun.file('./src/format.js').text();
const cryptoJs       = await Bun.file('./src/crypto.js').text();
const cipherSuitesJs = await Bun.file('./src/cipher-suites.js').text();
const appJs          = await Bun.file(scriptPath).text();
const script = [formatJs, cryptoJs, cipherSuitesJs, appJs].join('\n\n');

for (const placeholder of ['{{APP_STYLE}}', '{{LEVIATHAN_BUNDLE}}', '{{APP_SCRIPT}}']) {
	if (!template.includes(placeholder)) {
		process.stderr.write(`Error: placeholder ${placeholder} not found in template\n`);
		process.exit(1);
	}
}

mkdirSync(outputDir, { recursive: true });

const html = template
	.replace('{{APP_STYLE}}', style)
	.replace('{{LEVIATHAN_BUNDLE}}', bundle)
	.replace('{{APP_SCRIPT}}', script);

await Bun.write(outputPath, html);

const size = statSync(outputPath).size;
const kb = (size / 1024).toFixed(1);
process.stdout.write(`Built: ${outputPath}  (${kb} KB)\n`);
